### ISSUE TITLE
[BUG] - Date Formatting Fatal Error

### ISSUE THREAD

**Issue by DatTomato** [DorielRivalet/mhfz-overlay#168] opened 2023-08-17 14:07 UTC
### Is there an existing issue for this?

- [X] I have searched the existing issues

### What happened?

A after launching the overlay experienced fatal error. Here is my crash log
[logs.log](https://github.com/DorielRivalet/mhfz-overlay/files/12370279/logs.log)

### How often does the bug occur?

Always

### What operating system are you using?

Windows 10 

### What version of the program are you using?

v0.27.3

### What version of the game are you using?

High-Grade Edition

### Quest ID

0

**Comment by DorielRivalet** [comment] 2023-08-17 22:01
The issue is because of the format of the dates which used to be dependent on the user's system settings. A fix would be converting the dates to a standard format.

**Comment by DorielRivalet** [comment] 2023-08-17 22:10
Does the issue still occur if you use version 0.29.1?

**Comment by DatTomato** [comment] 2023-08-19 09:30
Yes the issue still persists after updating

**Comment by DatTomato** [comment] 2023-08-26 07:20
How do I convert my system date to a standard format?

**Comment by DorielRivalet** [comment] 2023-08-26 07:35
You have to wait until I make the code to automatically convert all the dates in the wrong format into the new format, so when the next version is released.

A temporary fix could be renaming (or moving to another folder) the database file, which is called `MHFZ_Overlay.sqlite`, thus making the program create a new one at startup.  The file is found in the game's directory inside a database folder.

**Closed** 2023-09-01 21:43 UTC
Labels: bug
