### ISSUE TITLE
[BUG] - Damage calculator is unstable

### ISSUE THREAD

**Issue by ezemania2** [DorielRivalet/mhfz-overlay#32] opened 2022-11-23 00:17 UTC
### What happened?

the damage calculator make the soft crash

### What version of the program are you using?

Latest version

### What version of the game are you using?

High-Grade Edition

**Comment by DorielRivalet** [comment] 2022-11-23 09:21
The cause is spam clicking on the dropdown options. A fix is yet to be done.

**Comment by DorielRivalet** [comment] 2023-05-28 07:12
I'm closing this for now, see DorielRivalet/frontier-compendium#1 for a related issue. Once the new calculator is made, the overlay's browser would have an updated link and users would be redirected there instead.

I'm leaving this issue pinned until the new calculator is finished.

**Closed by DorielRivalet** 2023-05-28 07:12 UTC
Labels: bug

**Comment by DorielRivalet** [comment] 2024-06-20 06:06
Check the [new calculator](https://wycademy.vercel.app/arena#damage-calculator). The old one is being deleted in August.

**Comment by ezemania2** [comment] 2024-06-20 08:07
Sure! I will check it when I will at work

Le jeu. 20 juin 2024, 08:06, Doriel Rivalet ***@***.***> a
écrit :
